name: Build and Sign Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build-and-sign:
    runs-on: windows-latest
    env:
      REDIS_URL: ${{ secrets.REDIS_URL }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
        
    - name: Build executable
      run: |
        pyinstaller --onefile --name sc-command --add-data ".env:." sc_command.py
        
    - name: Azure Code Signing
      uses: azure/trusted-signing-action@v0.5.1
      with:
        azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
        azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        endpoint: https://eus.codesigning.azure.net/
        code-signing-account-name: ${{ secrets.CODE_SIGNING_ACCOUNT_NAME }}
        certificate-profile-name: ${{ secrets.CERTIFICATE_PROFILE_NAME }}
        files-folder: 'dist'
        files-folder-filter: '*.exe'
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: sc-command-signed
        path: dist/sc-command.exe 